on: [push]
jobs:
  test:
    name: dotnet build
    runs-on: docker
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
            dotnet-version: '10.0.x'
      - run: dotnet build

