<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Core\Types.fs" />
        <Compile Include="Maths\Types.fs" />
        <Compile Include="Maths\Intersections.fs" />
        <Compile Include="Geometry\Types.fs" />
        <Compile Include="Geometry\Shapes\Quad.fs" />
        <Compile Include="Cameras\Core.fs" />
        <Compile Include="Cameras\FreeLookCamera.fs" />
        <Folder Include="Grids\TwoDimensional\" />
        <Folder Include="Grids\ThreeDimensional\" />
        <Compile Include="Animations\Armatures\Types.fs" />
        <Compile Include="Animations\Armatures\Impl.fs" />
        <Compile Include="Animations\Clips\Types.fs" />
        <Compile Include="Animations\Clips\Impl.fs" />
        <Compile Include="Serialization\Common.fs" />

        <Compile Include="Serialization\Json\Impl.fs" />

        <Compile Include="Serialization\Json\Extensions\Common.fs" />
        <Compile Include="Serialization\Json\Extensions\Maths.fs" />
        <Compile Include="Serialization\Json\Extensions\Geometry.fs" />
        <Compile Include="Serialization\Json\JsonSerializer.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FsToolbox\FsToolbox.fsproj" />
    </ItemGroup>

</Project>
